/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.apis

import com.trenicalea.trintedapp.models.*
import com.trenicalea.trintedapp.infrastructure.*

class OrdineControllerApi(basePath: kotlin.String = "https://localhost:8443") : ApiClient(basePath) {

    /**
     * 
     * 
     * @param acquirente  
     * @param articoloDto  
     * @return OrdineDto
     */
    @Suppress("UNCHECKED_CAST")
    fun add2(acquirente: kotlin.Long, articoloDto: ArticoloDto): OrdineDto {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            put("acquirente", listOf(acquirente.toString()))
            put("articoloDto", listOf(articoloDto.toString()))
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/order-api/orders", query = localVariableQuery
        )
        val response = request<OrdineDto>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as OrdineDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @return kotlin.Array<OrdineDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun all1(): kotlin.Array<OrdineDto> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/order-api/orders"
        )
        val response = request<kotlin.Array<OrdineDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<OrdineDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param orderId  
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    fun delete2(orderId: kotlin.Long): kotlin.String {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/order-api/orders/{orderId}".replace("{" + "orderId" + "}", "$orderId")
        )
        val response = request<kotlin.String>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return kotlin.Array<OrdineDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getByAcquirente(id: kotlin.Long): kotlin.Array<OrdineDto> {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            put("id", listOf(id.toString()))
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/order-api/buyer", query = localVariableQuery
        )
        val response = request<kotlin.Array<OrdineDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<OrdineDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param orderId  
     * @return OrdineDto
     */
    @Suppress("UNCHECKED_CAST")
    fun getById1(orderId: kotlin.Long): OrdineDto {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/order-api/orders/{orderId}".replace("{" + "orderId" + "}", "$orderId")
        )
        val response = request<OrdineDto>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as OrdineDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return kotlin.Array<OrdineDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getByVenditore(id: kotlin.Long): kotlin.Array<OrdineDto> {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            put("id", listOf(id.toString()))
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/order-api/seller", query = localVariableQuery
        )
        val response = request<kotlin.Array<OrdineDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<OrdineDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
