/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

/**
 * 
 * @param id 
 * @param titolo 
 * @param descrizione 
 * @param prezzo 
 * @param immagini 
 * @param utente 
 * @param ordineAssociato 
 * @param categoria 
 * @param condizioni 
 */
data class Articolo (

    val id: Long? = null,
    val titolo: String? = null,
    val descrizione: String? = null,
    val prezzo: Double? = null,
    val immagini: Array<String>? = null,
    val utente: Utente? = null,
    val ordineAssociato: Ordine? = null,
    val categoria: Categoria? = null,
    val condizioni: Condizioni? = null
) {
    /**
    * 
    * Values: DONNA,UOMO,BAMBINI,CASA,INTRATTENIMENTO,ANIMALI
    */
    enum class Categoria(val value: String){
        DONNA("DONNA"),
        UOMO("UOMO"),
        BAMBINI("BAMBINI"),
        CASA("CASA"),
        INTRATTENIMENTO("INTRATTENIMENTO"),
        ANIMALI("ANIMALI");
    }
    /**
    * 
    * Values: NUOVO,OTTIME,BUONE,DISCRETE
    */
    enum class Condizioni(val value: String){
        NUOVO("NUOVO"),
        OTTIME("OTTIME"),
        BUONE("BUONE"),
        DISCRETE("DISCRETE");
    }
}