/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

import android.graphics.Bitmap
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param id
 * @param titolo
 * @param descrizione
 * @param prezzo
 * @param immagini
 * @param utente
 * @param ordineAssociato
 * @param categoria
 * @param condizioni
 */
@JsonClass(generateAdapter = true)
data class Articolo(

    val id: Long? = null,
    val titolo: String? = null,
    val descrizione: String? = null,
    val prezzo: Double? = null,
    @Json(name = "immagini")
    val immagini: List<Bitmap>,
    val utente: Utente? = null,
    val ordineAssociato: Ordine? = null,
    val categoria: Categoria? = null,
    val condizioni: Condizioni? = null
) {
    /**
     *
     * Values: DONNA,UOMO,BAMBINI,CASA,INTRATTENIMENTO,ANIMALI
     */
    enum class Categoria(val value: String) {
        DONNA("DONNA"),
        UOMO("UOMO"),
        BAMBINI("BAMBINI"),
        CASA("CASA"),
        INTRATTENIMENTO("INTRATTENIMENTO"),
        ANIMALI("ANIMALI");
    }

    /**
     *
     * Values: NUOVO,OTTIME,BUONE,DISCRETE
     */
    enum class Condizioni(val value: String) {
        NUOVO("NUOVO"),
        OTTIME("OTTIME"),
        BUONE("BUONE"),
        DISCRETE("DISCRETE");
    }
}