/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

/**
 *
 * @param id
 * @param acquirente
 * @param venditore
 * @param dataAcquisto
 * @param articolo
 * @param prezzoFinale
 * @param recensioneOrdine
 * @param indirizzo
 */
data class Ordine(

    val id: Long? = null,
    val acquirente: Utente? = null,
    val venditore: Utente? = null,
    val dataAcquisto: java.time.LocalDate? = null,
    val articolo: Articolo? = null,
    val prezzoFinale: Long? = null,
    val recensioneOrdine: Recensione? = null,
    val indirizzo: Indirizzo? = null
)