/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

/**
 *
 * @param id
 * @param dataAcquisto
 * @param acquirente
 * @param venditore
 * @param indirizzo
 */
data class OrdineDto(

    val id: Long? = null,
    val dataAcquisto: java.time.LocalDate,
    val acquirente: Utente? = null,
    val venditore: Utente? = null,
    val indirizzo: Indirizzo? = null
) {
    companion object {
        fun validateVia(via: String): Boolean {
            return via.isNotEmpty() && via.length > 5
        }

        fun validateCivico(civico: String): Boolean {
            return civico.isNotEmpty()
        }

        fun validatePaese(paese: String): Boolean {
            return paese.isNotEmpty() && paese.length > 3
        }
    }
}