/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models


/**
 *
 * @param totalPages
 * @param totalElements
 * @param pageable
 * @param numberOfElements
 * @param number
 * @param sort
 * @param first
 * @param last
 * @param size
 * @param content
 * @param empty
 */
data class PageRecensioneDto(

    val totalPages: Int? = null,
    val totalElements: Long? = null,
    val pageable: PageableObject? = null,
    val numberOfElements: Int? = null,
    val number: Int? = null,
    val sort: SortObject? = null,
    val first: Boolean? = null,
    val last: Boolean? = null,
    val size: Int? = null,
    val content: Array<RecensioneDto>? = null,
    val empty: Boolean? = null
) {
}