/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass


/**
 *
 * @param id
 * @param rating
 * @param commento
 * @param destinatario
 * @param autore
 * @param ordine
 */
@JsonClass(generateAdapter = true)
data class Recensione(

    val id: Long? = null,
    val rating: Float,
    val commento: String? = null,
    @Json(name = "destinatario")
    val destinatario: Utente? = null,
    @Json(name = "autore")
    var autore: Utente? = null,
    val ordine: Ordine? = null
)