/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

import android.graphics.Bitmap

/**
 *
 * @param id
 * @param nome
 * @param cognome
 * @param immagine
 * @param indirizzo
 * @param recensioniRicevute
 * @param articoli
 * @param preferiti
 * @param credenziali
 * @param isAdmin
 * @param ordiniUtente
 * @param saldo
 * @param ratingGenerale
 */
data class Utente(

    val id: Long? = null,
    val nome: String? = null,
    val cognome: String? = null,
    val immagine: Bitmap? = null,
    val indirizzo: Indirizzo? = null,
    val recensioniRicevute: Array<Recensione>? = null,
    val articoli: Array<Articolo>? = null,
    val preferiti: Array<Articolo>? = null,
    val credenziali: Credenziali,
    val isAdmin: Boolean? = null,
    val ordiniUtente: Array<Ordine>? = null,
    val saldo: Double? = null,
    val ratingGenerale: Float? = null
) {
}