/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.trenicalea.trintedapp.models

import android.graphics.Bitmap
import com.trenicalea.trintedapp.apis.UtenteControllerApi


/**
 * 
 * @param id 
 * @param immagine 
 * @param credenzialiUsername 
 * @param ratingGenerale 
 */
data class UtenteBasicDto (

    val id: Long,
    val immagine: Bitmap? = null,
    val credenzialiUsername: String,
    val ratingGenerale: Float? = null
) {

    companion object {

        private val _userApi: UtenteControllerApi = UtenteControllerApi()
        fun validateUsername(username: String): Boolean {
            return _userApi.all().find { it.credenzialiUsername == username } != null
        }
    }

}